package com.myspace.form_rendering;

/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "order-object")
@XmlAccessorType(XmlAccessType.FIELD)
public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String orderNumber;
	private java.lang.String customer;
	private java.lang.String address;
	private java.util.List<com.myspace.form_rendering.Item> items;

	public Order() {
	}

	public java.lang.String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(java.lang.String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public java.lang.String getCustomer() {
		return this.customer;
	}

	public void setCustomer(java.lang.String customer) {
		this.customer = customer;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.util.List<com.myspace.form_rendering.Item> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.myspace.form_rendering.Item> items) {
		this.items = items;
	}

	public Order(java.lang.String orderNumber, java.lang.String customer,
			java.lang.String address,
			java.util.ArrayList<com.myspace.form_rendering.Item> items) {
		this.orderNumber = orderNumber;
		this.customer = customer;
		this.address = address;
		this.items = items;
	}

}