package com.jboss.soap.service.acmedemo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-07-23T13:31:49.031+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", name = "AcmeDemoInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface AcmeDemoInterface {

    @WebMethod(action = "http://service.soap.jboss.com/AcmeDemo/listAvailablePlanes")
    @RequestWrapper(localName = "listAvailablePlanes", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanes")
    @ResponseWrapper(localName = "listAvailablePlanesResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.jboss.soap.service.acmedemo.Flight listAvailablePlanes(
        @WebParam(name = "in", targetNamespace = "")
        com.jboss.soap.service.acmedemo.FlightRequest in
    );

    @WebMethod
    @RequestWrapper(localName = "cancelBooking", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.CancelBooking")
    @ResponseWrapper(localName = "cancelBookingResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.CancelBookingResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int cancelBooking(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "bookFlights", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.BookFlights")
    @ResponseWrapper(localName = "bookFlightsResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.BookFlightsResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String bookFlights(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
