package something


global org.drools.Person prs

declare Car
   name: String
   type: String
end

declare Result
	value: Integer
	explanation: String
end



rule "wagons"
 dialect "mvel"
 when
   Car(name == "saab", type == "wagon")
   r: Result()
 then
   r.value = 42
   r.explanation = "just cause it is"
end

rule "cars"
 dialect "mvel"
 when
   Car(type=="car")
   r: Result()
 then
   r.value = 40
   r.explanation = "not as useful"
end

rule "another"
  when
   Car()
  then
    prs.setStatus("crazy");
end



