/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kie.xxx

import org.kie.model.order.Order
import org.kie.model.order.Order.OrderItem

global java.util.List list1;
global java.util.List list2;

global org.kie.model.order.Order order


rule orderRule
when
    $i : Order()
then
    list1.add( $i );
end

rule orderItemRule1
when
    $i : OrderItem( price > 6)
then
    list1.add( $i );
end

rule orderItemRule2
when
    $i : OrderItem( price < 6)
then
    list2.add( $i );
end
