/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.kie.integration.testcoverage.instrumentation;

import org.kie.integration.testcoverage.model.instrumentation.Person;
import org.kie.integration.testcoverage.model.instrumentation.Dog;
import org.kie.integration.testcoverage.model.instrumentation.Cat;

global java.util.List results

rule "person's pets"
when
  Person( pet: /pets )
then
  results.add(pet.getName());
end

rule "give a dog to an adult person without a dog"
when
  person: Person( /age[ this >= 18 ] )
  not Person( this == person, /pets{ #Dog } )
then
  person.addPet(new Dog("Lassie", 1));
end

rule "give a cat to an adult person without a cat"
when
  person: Person( /age[ this >= 18 ] )
  not Person( this == person, /pets{ #Cat } )
then
  person.addPet(new Cat("The Cat", 1));
end
