
package org.kie.remote.services.ws.sei.deployment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.kie.remote.services.ws.common.KieRemoteWebServiceException;
import org.kie.services.shared.ServicesVersion;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeploymentService", targetNamespace = DeploymentWebService.NAMESPACE)
public interface DeploymentWebService {

    final static String NAMESPACE = "http://services.remote.kie.org/" + ServicesVersion.VERSION + "/deploy";
    
    @WebResult(targetNamespace = "manage")
    @RequestWrapper(localName = "manage", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperDeploymentIdRequest")
    @ResponseWrapper(localName = "manageResponse", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperDeploymentInfoResponse")
    public DeploymentInfoResponse manage(@WebParam(name = "arg0", targetNamespace = "") DeploymentIdRequest arg0) throws KieRemoteWebServiceException;

    @WebMethod(action = "urn:GetProcessDefinitionIds")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionIds", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperGetProcessDefinitionIds")
    @ResponseWrapper(localName = "getProcessDefinitionIds", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperGetProcessDefinitionIds")
    public ProcessIdsResponse getProcessDefinitionIds(@WebParam(name = "arg0", targetNamespace = "") DeploymentIdRequest arg0) throws KieRemoteWebServiceException;

    @WebMethod(action = "urn:GetStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperDeploymentId")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = NAMESPACE, className = "org.kie.remote.services.ws.wsdl.generated.WrapperDeploymentInfo")
    public ProcessDefinitionResponse getProcessDefinition(@WebParam(name = "arg0", targetNamespace = "") DeploymentIdRequest arg0) throws KieRemoteWebServiceException;

}
