/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

import java.util.List;

global List list

rule "First rule in first activation group" @Propagation(IMMEDIATE)
activation-group "first-group"
    salience 10
when
then
    list.add("First rule in first activation group executed");
end

rule "Second rule in first activation group" @Propagation(IMMEDIATE)
activation-group "first-group"
    salience 5
when
then
    list.add("Second rule in first activation group executed");
end

rule "Rule without activation group" @Propagation(IMMEDIATE)
    salience 2
when
then
    list.add("Rule without activation group executed");
end
