package com.myspace.demo20210908applicant;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Applicant ID")
	private long applicantID;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("SSN")
	private java.lang.String SSN;
	@org.kie.api.definition.type.Label("US Citizen")
	private boolean USCitizen;
	public Applicant() {
	}

	public long getApplicantID() {
		return this.applicantID;
	}

	public void setApplicantID(long applicantID) {
		this.applicantID = applicantID;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getSSN() {
		return this.SSN;
	}

	public void setSSN(java.lang.String SSN) {
		this.SSN = SSN;
	}

	public boolean isUSCitizen() {
		return this.USCitizen;
	}

	public void setUSCitizen(boolean USCitizen) {
		this.USCitizen = USCitizen;
	}

	@Override
	public String toString() {
		return "Applicant [SSN=" + SSN + ", USCitizen=" + USCitizen
				+ ", address=" + address + ", applicantID=" + applicantID
				+ ", name=" + name + "]";
	}

	public Applicant(java.lang.Long applicantID, java.lang.String name,
			java.lang.String address, java.lang.String SSN, java.lang.Boolean USCitizen) {
		this.applicantID = applicantID;
		this.name = name;
		this.address = address;
		this.SSN = SSN;
		this.USCitizen = USCitizen;
	}

}
