package org.acme.ticket_support;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Component implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String version;
   private java.lang.String path;
   private java.lang.String problemDescription;

   public Component()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getVersion()
   {
      return this.version;
   }

   public void setVersion(java.lang.String version)
   {
      this.version = version;
   }

   public java.lang.String getPath()
   {
      return this.path;
   }

   public void setPath(java.lang.String path)
   {
      this.path = path;
   }

   public java.lang.String getProblemDescription()
   {
      return this.problemDescription;
   }

   public void setProblemDescription(java.lang.String problemDescription)
   {
      this.problemDescription = problemDescription;
   }

   public Component(java.lang.String name, java.lang.String version,
         java.lang.String path, java.lang.String problemDescription)
   {
      this.name = name;
      this.version = version;
      this.path = path;
      this.problemDescription = problemDescription;
   }
    
   public String toString()
   {
       return "{'name': '" + this.name + "', " +
       "'version': '" + this.version + "', " +
       "'path': '" + this.path +  "', " +
       "'problemDescription': '" + this.problemDescription + "'}";
   }
}