/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

import java.util.List;

global List list

rule "Rule in first ruleflow group" @Propagation(IMMEDIATE)
    salience 10
    ruleflow-group "ruleflow-group1"
when
then
    list.add("Rule from first ruleflow group executed");
end

rule "Rule in second ruleflow group" @Propagation(IMMEDIATE)
    salience 100 // higher salience should not make the rule fire first as it is in the second ruleflow-group
    ruleflow-group "ruleflow-group2"
when
then
    list.add("Rule from second ruleflow group executed");
end
