/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.kie.server.testing.agenda;

import java.util.List;

global List list

rule "Rule in first agenda group" @Propagation(IMMEDIATE)
agenda-group "first-agenda"
    salience 10
when
then
    list.add("Rule in first agenda group executed");
end

rule "Rule without agenda group" @Propagation(IMMEDIATE)
    salience 100 // higher salience should not make the rule fire first as it is in the main agenda group
when
then
    list.add("Rule without agenda group executed");
end
