/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.kie.examples.cdi.basic

import java.util.List
import org.drools.jboss.integration.model.TestFactDeclaredInJar

global List resultList

declare TestFactDeclaredInDrl
    name: String
end

rule "Rule testing DRL fact"
when
    matchedFact: TestFactDeclaredInDrl()
then
    resultList.add(matchedFact);
end

rule "Rule testing jar fact"
when
    matchedFact: TestFactDeclaredInJar()
then
    resultList.add(matchedFact);
    insert(new TestFactDeclaredInDrl());
end
