package com.myspace.test.data;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;


    private java.lang.String name;

    private java.lang.String surname;

    public Person() {}

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getSurname() {
        return this.surname;
    }

    public void setSurname(java.lang.String surname) {
        this.surname = surname;
    }

    public Person(java.lang.String name, java.lang.String surname) {
        this.name = name;
        this.surname = surname;
    }

    @Override
    public String toString() {
        return "person [name=" + this.name + ", surname=" + surname + "]";
    }

}
